# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c476929a49b5d7cd65c768123e36b9011f64c7cb156f6713473c0d74eb60d51e48b930cc51b83487a820e831679ddd735ca6341a4719b5edc028ce3d899a178

test:
  secret_key_base: 15c56ec6257dda643671e6a85f22e3e6f44b17e1e25c6be7e45d9936df0d31d8474d3343859b8d5e74f3e3a8faff512f232099b861a06401e94700c0a77aeb4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
